leftnav:
- identifier: 96976d03-6408-40a4-8928-bf0f76854f7d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 3c893030-4c7c-4eae-9b25-e9ffcd7f10fd
  name: Course Outline
  pageRef: /pages/course-outline
  weight: 20
- identifier: 85195152-4d1a-4b6a-893f-edd7b584c354
  name: Course Introduction
  pageRef: /pages/course-introduction
  weight: 30
- identifier: 33ff81fb-0b04-4a38-bec0-060ac3912238
  name: Video Modules
  pageRef: /pages/video-modules
  weight: 40
- identifier: 673e61d6-5190-4ae0-93d7-183dc6edb1f4
  name: 'Level 0: Understanding Innovating'
  pageRef: /pages/level-0-understanding-innovating-team-building
  weight: 50
- identifier: de76bb64-a10d-4bcc-9dab-57d4bd3064e6
  name: 'Level 1: Exploring for Opportunities'
  pageRef: /pages/level-1-exploring-for-opportunities
  weight: 60
- identifier: 9c96d037-d978-44f1-be51-9c8bf6ddd048
  name: 'Level 2: Innovating as Scaling-Up'
  pageRef: /pages/level-2-innovating-as-scaling-up
  weight: 70
- identifier: d1919e63-81a5-4157-92e0-16d5a1f33e3a
  name: 'Level 3: Systematizing For Impact at Scale'
  pageRef: /pages/level-3-systematizing-for-impact-at-scale
  weight: 80
- identifier: 12e9ac17-3225-4a4d-bad1-4aadfe237406
  name: Assignments
  pageRef: /pages/iteams-project
  weight: 90
